name: cosmosdb-with-fastapi deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'cosmosdb-with-fastapi/**'
    - '.github/workflows/build-deploy-api.yaml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: cosmosdbtest.azurecr.io
          username: ${{ env.COSMOSDB_FASTAPI_REGISTRY_USERNAME }}
          password: ${{ env.COSMOSDB_FASTAPI_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: cosmosdbtest.azurecr.io/cosmosdb-fast-api:${{ github.sha }} , cosmosdbtest.azurecr.io/cosmosdb-fast-api:latest
          file: Dockerfile
          context: ./.
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: TEST
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.COSMOSDB_FASTAPI_AZURE_CREDENTIALS }}
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cosmosdb-with-fastapi -g cosmosdb-with-fastapi --server cosmosdbtest.azurecr.io --username  ${{ secrets.COSMOSDB_FASTAPI_REGISTRY_USERNAME }} --password ${{ secrets.COSMOSDB_FASTAPI_REGISTRY_PASSWORD }}
            az containerapp update -n cosmosdb-with-fastapi -g cosmosdb-with-fastapi --image cosmosdbtest.azurecr.io/cosmosdb-fast-api:${{ github.sha }}